Repository special-warriors/conal-back, pull requests merged in 2025-05, with the labels that each got.

#6 [feat] 사용자는 주간 투표 기능을 활성화/비활성화할 수 있다
  build.gradle
  src/main/java/com/specialwarriors/conal/common/exception/ExceptionResponse.java
  src/main/java/com/specialwarriors/conal/common/exception/GeneralException.java
  src/main/java/com/specialwarriors/conal/common/exception/GlobalExceptionHandler.java
  src/main/java/com/specialwarriors/conal/github_repo/domain/GithubRepo.java
  src/main/java/com/specialwarriors/conal/github_repo/exception/GithubRepoException.java
  src/main/java/com/specialwarriors/conal/notification/controller/NotificationRestController.java
  src/main/java/com/specialwarriors/conal/notification/converter/NotificationTypeConverter.java
  src/main/java/com/specialwarriors/conal/notification/domain/NotificationAgreement.java
  src/main/java/com/specialwarriors/conal/notification/dto/request/NotificationAgreementUpdateRequest.java
  src/main/java/com/specialwarriors/conal/notification/enums/NotificationType.java
  src/main/java/com/specialwarriors/conal/notification/exception/NotificationAgreementException.java
  src/main/java/com/specialwarriors/conal/notification/repository/NotificationAgreementRepository.java
  src/main/java/com/specialwarriors/conal/notification/service/NotificationAgreementQuery.java
  src/main/java/com/specialwarriors/conal/notification/service/NotificationService.java
  src/main/java/com/specialwarriors/conal/user/domain/User.java
  src/main/java/com/specialwarriors/conal/user/exception/UserException.java
  src/main/java/com/specialwarriors/conal/user/repository/UserRepository.java
  src/main/java/com/specialwarriors/conal/user/service/UserQuery.java
Labels: feat

#14 [fix] CD 과정에서 서브모듈의 main 브랜치를 참조하도록 수정
  .github/workflows/cd.yml
  .gitmodules
Labels: fix

#16 [fix] JWT 필터 예외 경로 설정 방식 수정
  src/main/java/com/specialwarriors/conal/common/auth/jwt/JwtFilter.java
Labels: fix

#19 [feat] 세션 기반으로 인증과 인가를 검증한다
  build.gradle
  src/main/java/com/specialwarriors/conal/common/auth/controller/AuthController.java
  src/main/java/com/specialwarriors/conal/common/auth/exception/AuthException.java
  src/main/java/com/specialwarriors/conal/common/auth/jwt/JwtFilter.java
  src/main/java/com/specialwarriors/conal/common/auth/jwt/JwtTokenProvider.java
  src/main/java/com/specialwarriors/conal/common/auth/jwt/JwtTokenResponse.java
  src/main/java/com/specialwarriors/conal/common/auth/jwt/domain/RefreshToken.java
  src/main/java/com/specialwarriors/conal/common/auth/jwt/dto/TokenReissueRequest.java
  src/main/java/com/specialwarriors/conal/common/auth/jwt/repository/RefreshTokenRepository.java
  src/main/java/com/specialwarriors/conal/common/auth/oauth/CustomLogoutHandler.java
  src/main/java/com/specialwarriors/conal/common/auth/oauth/CustomOAuth2FailureHandler.java
  src/main/java/com/specialwarriors/conal/common/auth/oauth/CustomOAuth2SuccessHandler.java
  src/main/java/com/specialwarriors/conal/common/auth/oauth/CustomOAuth2UserService.java
  src/main/java/com/specialwarriors/conal/common/auth/oauth/CustomUserDetails.java
  src/main/java/com/specialwarriors/conal/common/auth/oauth/CustomUserDetailsService.java
  src/main/java/com/specialwarriors/conal/common/auth/oauth/CustomUserDetailsServiceImpl.java
  src/main/java/com/specialwarriors/conal/common/auth/service/AuthService.java
  src/main/java/com/specialwarriors/conal/common/auth/session/SessionAuthenticationFilter.java
  src/main/java/com/specialwarriors/conal/common/auth/session/SessionManager.java
  src/main/java/com/specialwarriors/conal/common/config/RedisConfig.java
  src/main/java/com/specialwarriors/conal/common/config/SecurityConfig.java
  src/main/java/com/specialwarriors/conal/user/controller/UserController.java
  src/main/java/com/specialwarriors/conal/user/domain/User.java
  src/main/java/com/specialwarriors/conal/user/repository/UserRepository.java
  src/main/java/com/specialwarriors/conal/user/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/templates/home.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login/failure.html
  src/main/resources/templates/login/success.html
  src/main/resources/templates/main/home.html
  src/main/resources/templates/main/index.html
  src/main/resources/templates/user/mypage.html
  src/test/java/com/specialwarriors/conal/ConalApplicationTests.java
  src/test/resources/application-test.yml
Labels: feat

#21 [feat] 사용자는 회원 탈퇴를 할 수 있다
  src/main/java/com/specialwarriors/conal/common/auth/exception/AuthException.java
  src/main/java/com/specialwarriors/conal/common/auth/oauth/CustomLogoutHandler.java
  src/main/java/com/specialwarriors/conal/common/auth/oauth/CustomOAuth2SuccessHandler.java
  src/main/java/com/specialwarriors/conal/common/auth/oauth/CustomOAuth2UserService.java
  src/main/java/com/specialwarriors/conal/common/auth/oauth/GithubOAuth2WebClient.java
  src/main/java/com/specialwarriors/conal/common/config/SecurityConfig.java
  src/main/java/com/specialwarriors/conal/common/config/WebClientConfig.java
  src/main/java/com/specialwarriors/conal/common/config/WebConfig.java
  src/main/java/com/specialwarriors/conal/github/controller/GitHubController.java
  src/main/java/com/specialwarriors/conal/user/controller/UserController.java
  src/main/java/com/specialwarriors/conal/user/domain/User.java
  src/main/java/com/specialwarriors/conal/user/repository/UserRepository.java
  src/main/java/com/specialwarriors/conal/user/service/UserService.java
  src/main/resources/templates/login/success.html
  src/main/resources/templates/main/home.html
  src/main/resources/templates/user/delete-success.html
  src/main/resources/templates/user/mypage.html
  src/test/java/com/specialwarriors/conal/ConalApplicationTests.java
  src/test/resource/application.yml
  src/test/resources/application-test.yml
Labels: feat

#24 [fix] 인증/인가 로직 수정
  src/main/java/com/specialwarriors/conal/common/auth/exception/AuthException.java
  src/main/java/com/specialwarriors/conal/common/auth/exception/CustomAuthException.java
  src/main/java/com/specialwarriors/conal/common/auth/jwt/JwtTokenProvider.java
  src/main/java/com/specialwarriors/conal/common/auth/oauth/CustomOAuth2FailureHandler.java
  src/main/java/com/specialwarriors/conal/common/auth/oauth/CustomOAuth2SuccessHandler.java
  src/main/java/com/specialwarriors/conal/common/auth/oauth/GithubOAuth2WebClient.java
  src/main/java/com/specialwarriors/conal/common/config/SecurityConfig.java
  src/main/resources/templates/main/home.html
  src/main/resources/templates/main/index.html
  src/main/resources/templates/user/mypage.html
Labels: fix

#28 [fix] 사용자, 레포지토리 화면 수정
  index.html
  src/main/java/com/specialwarriors/conal/github_repo/controller/GithubRepoController.java
  src/main/java/com/specialwarriors/conal/user/controller/UserController.java
  src/main/resources/templates/main/home.html
  src/main/resources/templates/repo/detail.html
  src/main/resources/templates/repo/form.html
Labels: fix

#30 [fix] 로그아웃 시 알림창 미출력 오류 수정
  src/main/resources/templates/main/home.html
Labels: fix

#41 [fix] 전반적인 코드 스타일 정리 및 포맷팅
  src/main/java/com/specialwarriors/conal/common/auth/exception/AuthException.java
  src/main/java/com/specialwarriors/conal/common/auth/jwt/JwtTokenProvider.java
  src/main/java/com/specialwarriors/conal/common/auth/oauth/CustomOAuth2FailureHandler.java
  src/main/java/com/specialwarriors/conal/common/auth/oauth/CustomOAuth2UserService.java
  src/main/java/com/specialwarriors/conal/common/auth/session/SessionAuthenticationFilter.java
  src/main/java/com/specialwarriors/conal/common/auth/session/SessionManager.java
  src/main/java/com/specialwarriors/conal/common/config/RedisConfig.java
  src/main/java/com/specialwarriors/conal/common/config/WebClientConfig.java
  src/main/java/com/specialwarriors/conal/common/exception/GlobalExceptionHandler.java
  src/main/java/com/specialwarriors/conal/contribution/scheduler/ContributionScheduler.java
  src/main/java/com/specialwarriors/conal/contribution/service/ContributionService.java
  src/main/java/com/specialwarriors/conal/github/controller/GitHubController.java
  src/main/java/com/specialwarriors/conal/github/dto/GitHubContributor.java
  src/main/java/com/specialwarriors/conal/github/service/GitHubService.java
  src/main/java/com/specialwarriors/conal/github_repo/controller/GithubRepoController.java
  src/main/java/com/specialwarriors/conal/github_repo/dto/GithubRepoMapper.java
  src/main/java/com/specialwarriors/conal/github_repo/repository/GithubRepoRepository.java
  src/main/java/com/specialwarriors/conal/github_repo/repository/GithubRepoRepositoryImpl.java
  src/main/java/com/specialwarriors/conal/github_repo/service/GithubRepoQuery.java
  src/main/java/com/specialwarriors/conal/github_repo/service/GithubRepoService.java
  src/main/java/com/specialwarriors/conal/notification/controller/NotificationRestController.java
  src/main/java/com/specialwarriors/conal/notification/repository/NotificationAgreementRepository.java
  src/main/java/com/specialwarriors/conal/notification/service/NotificationAgreementQuery.java
  src/main/java/com/specialwarriors/conal/notification/service/NotificationService.java
  src/main/java/com/specialwarriors/conal/user/service/UserService.java
  src/main/java/com/specialwarriors/conal/util/MailUtil.java
  src/main/java/com/specialwarriors/conal/util/UrlUtil.java
  src/main/java/com/specialwarriors/conal/vote/controller/VoteController.java
  src/main/java/com/specialwarriors/conal/vote/exception/VoteException.java
  src/main/java/com/specialwarriors/conal/vote/scheduler/VoteScheduler.java
  src/main/java/com/specialwarriors/conal/vote/service/VoteService.java
  src/main/resources/templates/repo/detail.html
  src/main/resources/templates/user/mypage.html
Labels: fix

#38 [test] 사용자 기능 단위 테스트 작성
  src/main/java/com/specialwarriors/conal/user/controller/UserController.java
  src/main/java/com/specialwarriors/conal/user/service/UserService.java
  src/test/java/com/specialwarriors/conal/UserServiceTest.java
Labels: test

#47 [test] 투표 기능 단위 테스트 작성
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .gitignore
  build.gradle
  src/main/java/com/specialwarriors/conal/common/auth/jwt/JwtTokenProvider.java
  src/main/java/com/specialwarriors/conal/github_repo/domain/GithubRepo.java
  src/main/java/com/specialwarriors/conal/github_repo/exception/GithubRepoException.java
  src/main/java/com/specialwarriors/conal/github_repo/service/GithubRepoQuery.java
  src/main/java/com/specialwarriors/conal/github_repo/service/GithubRepoService.java
  src/main/java/com/specialwarriors/conal/notification/service/NotificationService.java
  src/main/java/com/specialwarriors/conal/user/domain/User.java
  src/main/java/com/specialwarriors/conal/util/UrlUtil.java
  src/main/java/com/specialwarriors/conal/vote/dto/request/VoteSaveRequest.java
  src/main/java/com/specialwarriors/conal/vote/service/VoteService.java
  src/test/java/com/specialwarriors/conal/common/auth/jwt/JwtTokenProviderTest.java
  src/test/java/com/specialwarriors/conal/github_repo/service/GithubRepoQueryTest.java
  src/test/java/com/specialwarriors/conal/vote/service/VoteServiceTest.java
  src/test/resources/sql/github_repo/service/find_by_repository_id_test_setup.sql
  src/test/resources/sql/github_repo/service/find_by_user_id_and_repository_id_test_setup.sql
Labels: feat, chore, test
